; supervisord.conf: nginx, next, nest 프로세스 관리
; 각 프로세스는 예외 발생 시 재시작
[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/nginx-supervisor.log

[program:frontend]
command=sh -c "cd /app/frontend && npm run start"
autorestart=true
redirect_stderr=true
stdout_logfile=/app/frontend/next-supervisor.log

[program:backend]
command=sh -c "cd /app/backend && npm run start:prod"
autorestart=true
redirect_stderr=true
stdout_logfile=/app/backend/nest-supervisor.log
